# Config info for Plus server

PLUS_MONGO_URI = "mongodb://localhost:27017"
PLUS_DEFAULT_DB = "Plus"

PLUS_DATABASE_URI = "sqlite:///plus.db"

PLUS_UPLOAD_DIRECTORY = "~/.katten/plus/uploads"

PLUS_SESSION_EXPIRY = False
PLUS_SESSION_TIME = 60 * 60 * 24 * 180 # seconds
PLUS_GAMERTAG_MIN_LENGTH = 4
PLUS_GAMERTAG_MAX_LENGTH = 15
PLUS_PASSWORD_MIN_LENGTH = 4
PLUS_SESSION_TOKEN_BITS = 192

PLUS_USER_UPDATE_INTERVAL = 1200

PLUS_AUTO_REGISTER_GAMES = True

__all__ = [
	"PLUS_MONGO_URI",
	"PLUS_DEFAULT_DB",
	"PLUS_DATABASE_URI",
	"PLUS_UPLOAD_DIRECTORY",
	"PLUS_SESSION_EXPIRY",
	"PLUS_SESSION_TIME",
	"PLUS_GAMERTAG_MAX_LENGTH",
	"PLUS_GAMERTAG_MIN_LENGTH",
	"PLUS_PASSWORD_MIN_LENGTH",
	"PLUS_SESSION_TOKEN_BITS",
	"PLUS_USER_UPDATE_INTERVAL",
	"PLUS_AUTO_REGISTER_GAMES"
]
