# Config info for Plus server

PLUS_MONGO_URI = "mongodb://localhost:27017"
PLUS_DEFAULT_DB = "Plus"

PLUS_SESSION_TIME = 60 * 60 * 24 * 180 # seconds
PLUS_GAMERTAG_MIN_LENGTH = 4
PLUS_GAMERTAG_MAX_LENGTH = 15
PLUS_PASSWORD_MIN_LENGTH = 4
PLUS_SESSION_TOKEN_BITS = 192

PLUS_USER_UPDATE_INTERVAL = 1200

PLUS_AUTO_REGISTER_GAMES = True

__all__ = list(globals().keys())
